import { STORAGE_KEYS } from "../config.js";

export const languageNames = { pt:"Português", en:"English", es:"Español", fr:"Français", de:"Deutsch", it:"Italiano", nl:"Nederlands", pl:"Polski", ru:"Русский", tr:"Türkçe", ar:"العربية", hi:"हिन्दी", zh:"中文", ja:"日本語", ko:"한국어" };
const languageLocales = { pt:"pt-BR", en:"en-US", es:"es-ES", fr:"fr-FR", de:"de-DE", it:"it-IT", nl:"nl-NL", pl:"pl-PL", ru:"ru-RU", tr:"tr-TR", ar:"ar-SA", hi:"hi-IN", zh:"zh-CN", ja:"ja-JP", ko:"ko-KR" };
export const removeImageLabels = { pt:"Remover imagem", en:"Remove image", es:"Quitar imagen", fr:"Supprimer l’image", de:"Bild entfernen", it:"Rimuovi immagine", nl:"Afbeelding verwijderen", pl:"Usuń obraz", ru:"Удалить фон", tr:"Görseli kaldır", ar:"إزالة الصورة", hi:"चित्र हटाएँ", zh:"移除图片", ja:"画像を削除", ko:"이미지 제거" };
export const openSiteLabels = { pt:"Abrir site", en:"Open site", es:"Abrir sitio", fr:"Ouvrir le site", de:"Seite öffnen", it:"Apri sito", nl:"Site openen", pl:"Otwórz witrynę", ru:"Открыть сайт", tr:"Siteyi aç", ar:"فتح الموقع", hi:"साइट खोलें", zh:"打开网站", ja:"サイトを開く", ko:"사이트 열기" };
export const languageLabels = { pt:"Idioma", en:"Language", es:"Idioma", fr:"Langue", de:"Sprache", it:"Lingua", nl:"Taal", pl:"Język", ru:"Язык", tr:"Dil", ar:"اللغة", hi:"भाषा", zh:"语言", ja:"言語", ko:"언어" };
export const shortcutFilterLabels = { pt:"Atalhos", en:"Shortcuts", es:"Accesos", fr:"Raccourcis", de:"Verknüpfungen", it:"Scorciatoie", nl:"Snelkoppelingen", pl:"Skróty", ru:"Ярлыки", tr:"Kısayollar", ar:"اختصارات", hi:"शॉर्टकट", zh:"快捷方式", ja:"ショートカット", ko:"바로가기" };
export const pageTitleLabels = { pt:"Luma Search Abstraction — sua pesquisa, do seu jeito", en:"Luma Search Abstraction — search your way", es:"Luma Search Abstraction — busca a tu manera", fr:"Luma Search Abstraction — recherchez à votre façon", de:"Luma Search Abstraction — suche auf deine Art", it:"Luma Search Abstraction — cerca a modo tuo", nl:"Luma Search Abstraction — zoek op jouw manier", pl:"Luma Search Abstraction — wyszukuj po swojemu", ru:"Luma Search Abstraction — ищите по-своему", tr:"Luma Search Abstraction — kendi yönteminizle arayın", ar:"Luma Search Abstraction — ابحث بطريقتك", hi:"Luma Search Abstraction — अपने तरीके से खोजें", zh:"Luma Search Abstraction — 按你的方式搜索", ja:"Luma Search Abstraction — 自分らしく検索", ko:"Luma Search Abstraction — 나만의 방식으로 검색" };
export const clearLabels = { pt:"Limpar", en:"Clear", es:"Limpiar", fr:"Effacer", de:"Leeren", it:"Pulisci", nl:"Wissen", pl:"Wyczyść", ru:"Очистить", tr:"Temizle", ar:"مسح", hi:"साफ़ करें", zh:"清除", ja:"クリア", ko:"지우기" };
export const creatorLabels = { pt:"criado por", en:"created by", es:"creado por", fr:"créé par", de:"erstellt von", it:"creato da", nl:"gemaakt door", pl:"utworzone przez", ru:"создано", tr:"oluşturan", ar:"أنشأه", hi:"निर्माता", zh:"创建者", ja:"作成者", ko:"제작" };
export const translations = {
  pt:{all:"Selecionar todos",none:"Desselecionar todos",batch:"Pesquisar em lote",search:"Pesquisar",placeholder:"Digite sua pesquisa...",engines:"Mecanismos",where:"Onde pesquisar",hint:"Clique no site para torná-lo principal",space:"Espaço de pesquisa",title:"O que vamos descobrir hoje?",desc:"Pesquise no seu site favorito ou explore vários lugares de uma só vez.",storage:"Seus sites ficam salvos apenas neste navegador.",auth:"Requer autenticação",primary:"principal",assistant:"assistente — prompt copiado",shortcut:"atalho",sites:"sites",site:"site",empty:"Selecione ao menos um site para a pesquisa em lote."},
  en:{all:"Select all",none:"Deselect all",batch:"Batch search",search:"Search",placeholder:"Type your search...",engines:"Engines",where:"Where to search",hint:"Click a site to make it primary",space:"Search space",title:"What will we discover today?",desc:"Search your favorite site or explore several places at once.",storage:"Your sites are saved only in this browser.",auth:"Requires auth",primary:"primary",assistant:"assistant — prompt copied",shortcut:"shortcut",sites:"sites",site:"site",empty:"Select at least one site for batch search."},
  es:{all:"Seleccionar todos",none:"Deseleccionar todos",batch:"Búsqueda por lote",search:"Buscar",placeholder:"Escribe tu búsqueda...",engines:"Motores",where:"Dónde buscar",hint:"Haz clic para hacerlo principal",space:"Espacio de búsqueda",title:"¿Qué descubriremos hoy?",desc:"Busca en tu sitio favorito o explora varios a la vez.",storage:"Tus sitios se guardan solo en este navegador.",auth:"Requiere autenticación",primary:"principal",assistant:"asistente — prompt copiado",shortcut:"acceso",sites:"sitios",site:"sitio",empty:"Selecciona al menos un sitio."},
  fr:{all:"Tout sélectionner",none:"Tout désélectionner",batch:"Recherche groupée",search:"Rechercher",placeholder:"Saisissez votre recherche...",engines:"Moteurs",where:"Où rechercher",hint:"Cliquez pour le définir comme principal",space:"Espace de recherche",title:"Que découvrirons-nous aujourd’hui ?",desc:"Recherchez sur votre site favori ou explorez-en plusieurs.",storage:"Vos sites sont enregistrés dans ce navigateur.",auth:"Authentification requise",primary:"principal",assistant:"assistant — prompt copié",shortcut:"raccourci",sites:"sites",site:"site",empty:"Sélectionnez au moins un site."},
  de:{all:"Alle auswählen",none:"Alle abwählen",batch:"Stapelsuche",search:"Suchen",placeholder:"Suchbegriff eingeben...",engines:"Suchmaschinen",where:"Wo suchen",hint:"Klicken, um als Standard festzulegen",space:"Suchbereich",title:"Was entdecken wir heute?",desc:"Durchsuche deine Lieblingsseite oder mehrere gleichzeitig.",storage:"Deine Seiten bleiben in diesem Browser.",auth:"Anmeldung erforderlich",primary:"Standard",assistant:"Assistent — Prompt kopiert",shortcut:"Verknüpfung",sites:"Seiten",site:"Seite",empty:"Mindestens eine Seite auswählen."},
  it:{all:"Seleziona tutto",none:"Deseleziona tutto",batch:"Ricerca multipla",search:"Cerca",placeholder:"Digita la ricerca...",engines:"Motori",where:"Dove cercare",hint:"Clicca per renderlo principale",space:"Spazio di ricerca",title:"Cosa scopriremo oggi?",desc:"Cerca nel tuo sito preferito o esplorane diversi.",storage:"I siti restano salvati in questo browser.",auth:"Autenticazione richiesta",primary:"principale",assistant:"assistente — prompt copiato",shortcut:"scorciatoia",sites:"siti",site:"sito",empty:"Seleziona almeno un sito."},
  nl:{all:"Alles selecteren",none:"Alles deselecteren",batch:"Batch zoeken",search:"Zoeken",placeholder:"Typ je zoekopdracht...",engines:"Machines",where:"Waar zoeken",hint:"Klik om primair te maken",space:"Zoekruimte",title:"Wat ontdekken we vandaag?",desc:"Zoek op je favoriete site of op meerdere tegelijk.",storage:"Sites worden alleen in deze browser bewaard.",auth:"Authenticatie vereist",primary:"primair",assistant:"assistent — prompt gekopieerd",shortcut:"snelkoppeling",sites:"sites",site:"site",empty:"Selecteer minstens één site."},
  pl:{all:"Zaznacz wszystko",none:"Odznacz wszystko",batch:"Wyszukiwanie zbiorcze",search:"Szukaj",placeholder:"Wpisz zapytanie...",engines:"Wyszukiwarki",where:"Gdzie szukać",hint:"Kliknij, aby ustawić jako główną",space:"Przestrzeń wyszukiwania",title:"Co dziś odkryjemy?",desc:"Szukaj w ulubionej witrynie lub wielu naraz.",storage:"Witryny są zapisane tylko w tej przeglądarce.",auth:"Wymagane logowanie",primary:"główna",assistant:"asystent — prompt skopiowany",shortcut:"skrót",sites:"witryn",site:"witryna",empty:"Wybierz co najmniej jedną witrynę."},
  ru:{all:"Выбрать все",none:"Снять выбор",batch:"Пакетный поиск",search:"Поиск",placeholder:"Введите запрос...",engines:"Системы",where:"Где искать",hint:"Нажмите, чтобы сделать основным",space:"Пространство поиска",title:"Что откроем сегодня?",desc:"Ищите на любимом сайте или сразу на нескольких.",storage:"Сайты хранятся только в этом браузере.",auth:"Требуется вход",primary:"основной",assistant:"ассистент — запрос скопирован",shortcut:"ярлык",sites:"сайтов",site:"сайт",empty:"Выберите хотя бы один сайт."},
  tr:{all:"Tümünü seç",none:"Tüm seçimi kaldır",batch:"Toplu arama",search:"Ara",placeholder:"Aramanızı yazın...",engines:"Motorlar",where:"Nerede aranacak",hint:"Ana yapmak için tıklayın",space:"Arama alanı",title:"Bugün ne keşfedeceğiz?",desc:"Favori sitenizde veya birden çok yerde arayın.",storage:"Siteler yalnızca bu tarayıcıda saklanır.",auth:"Kimlik doğrulama gerekli",primary:"ana",assistant:"asistan — istem kopyalandı",shortcut:"kısayol",sites:"site",site:"site",empty:"En az bir site seçin."},
  ar:{all:"تحديد الكل",none:"إلغاء تحديد الكل",batch:"بحث متعدد",search:"بحث",placeholder:"اكتب بحثك...",engines:"المحركات",where:"أين تبحث",hint:"انقر لجعله رئيسيًا",space:"مساحة البحث",title:"ماذا سنكتشف اليوم؟",desc:"ابحث في موقعك المفضل أو عدة مواقع معًا.",storage:"تُحفظ المواقع في هذا المتصفح فقط.",auth:"يتطلب تسجيل الدخول",primary:"رئيسي",assistant:"مساعد — تم نسخ الطلب",shortcut:"اختصار",sites:"مواقع",site:"موقع",empty:"اختر موقعًا واحدًا على الأقل."},
  hi:{all:"सभी चुनें",none:"सभी हटाएँ",batch:"बैच खोज",search:"खोजें",placeholder:"अपनी खोज लिखें...",engines:"इंजन",where:"कहाँ खोजें",hint:"मुख्य बनाने के लिए क्लिक करें",space:"खोज स्थान",title:"आज हम क्या खोजेंगे?",desc:"अपनी पसंदीदा साइट या कई साइटों पर खोजें।",storage:"साइटें केवल इस ब्राउज़र में सहेजी जाती हैं।",auth:"लॉगिन आवश्यक",primary:"मुख्य",assistant:"सहायक — प्रॉम्प्ट कॉपी किया",shortcut:"शॉर्टकट",sites:"साइटें",site:"साइट",empty:"कम से कम एक साइट चुनें।"},
  zh:{all:"全选",none:"取消全选",batch:"批量搜索",search:"搜索",placeholder:"输入搜索内容...",engines:"搜索引擎",where:"在哪里搜索",hint:"点击设为主要站点",space:"搜索空间",title:"今天探索什么？",desc:"在你喜欢的网站或多个网站中搜索。",storage:"网站仅保存在此浏览器中。",auth:"需要登录",primary:"主要",assistant:"助手 — 提示词已复制",shortcut:"快捷方式",sites:"个网站",site:"个网站",empty:"请至少选择一个网站。"},
  ja:{all:"すべて選択",none:"すべて解除",batch:"一括検索",search:"検索",placeholder:"検索語を入力...",engines:"エンジン",where:"検索先",hint:"クリックしてメインに設定",space:"検索スペース",title:"今日は何を発見しますか？",desc:"お気に入りまたは複数のサイトを検索します。",storage:"サイトはこのブラウザにのみ保存されます。",auth:"ログインが必要",primary:"メイン",assistant:"アシスタント — プロンプトをコピー済み",shortcut:"ショートカット",sites:"サイト",site:"サイト",empty:"少なくとも1つ選択してください。"},
  ko:{all:"모두 선택",none:"모두 해제",batch:"일괄 검색",search:"검색",placeholder:"검색어를 입력하세요...",engines:"엔진",where:"검색 위치",hint:"클릭하여 기본으로 설정",space:"검색 공간",title:"오늘 무엇을 발견할까요?",desc:"즐겨찾는 사이트 또는 여러 사이트를 검색하세요.",storage:"사이트는 이 브라우저에만 저장됩니다.",auth:"로그인 필요",primary:"기본",assistant:"도우미 — 프롬프트 복사됨",shortcut:"바로가기",sites:"개 사이트",site:"사이트",empty:"사이트를 하나 이상 선택하세요."}
};

const chatTranslations = {
  pt:{aiTrigger:"Chat IA",aiEyebrow:"Comparador inteligente",aiTitle:"Chat IA unificado",aiSubtitle:"Uma pergunta, diferentes perspectivas.",aiSettingsTitle:"Conexões com provedores",aiSettingsWarning:"As chaves ficam somente neste navegador. Para produção, use um backend que mantenha os segredos no servidor.",aiCancel:"Cancelar",aiSave:"Salvar conexões",aiParticipants:"IAs participantes",aiEmptyTitle:"Compare respostas em segundos",aiEmptyDescription:"Faça uma pergunta para visualizar como diferentes assistentes abordam o mesmo tema.",aiSuggestionLaunch:"Estratégia de lançamento",aiSuggestionConcept:"Explicar um conceito",aiSuggestionExperience:"Analisar uma experiência",aiInputLabel:"Mensagem para as IAs",aiPlaceholder:"Pergunte para todas as IAs...",aiSend:"Enviar",aiNotice:"As mensagens são enviadas diretamente aos provedores selecionados. Custos e políticas de cada API se aplicam.",aiConfigured:"API configurada",aiMissingKey:"Sem chave",aiNoKeyRequired:"Não requer chave de API. A solicitação é enviada diretamente ao DuckDuckGo.",aiApiKey:"Chave da API",aiApiKeyPlaceholder:"Cole a chave da API",aiModel:"Modelo",aiYou:"Você",aiConfigure:"Configurar conexão",aiOpenSettings:"Configurar conexões",aiClose:"Fechar chat",aiConnectorMissing:"Conector não encontrado.",aiProviderSetup:"Configure a chave e o modelo deste provedor.",aiUnknownFailure:"Falha desconhecida."},
  en:{aiTrigger:"AI Chat",aiEyebrow:"Smart comparison",aiTitle:"Unified AI chat",aiSubtitle:"One question, different perspectives.",aiSettingsTitle:"Provider connections",aiSettingsWarning:"Keys stay only in this browser. In production, use a backend that keeps secrets on the server.",aiCancel:"Cancel",aiSave:"Save connections",aiParticipants:"Participating AIs",aiEmptyTitle:"Compare answers in seconds",aiEmptyDescription:"Ask a question to see how different assistants approach the same topic.",aiSuggestionLaunch:"Launch strategy",aiSuggestionConcept:"Explain a concept",aiSuggestionExperience:"Analyze an experience",aiInputLabel:"Message to the AIs",aiPlaceholder:"Ask all AIs...",aiSend:"Send",aiNotice:"Messages are sent directly to the selected providers. Each API's costs and policies apply.",aiConfigured:"API configured",aiMissingKey:"Missing key",aiNoKeyRequired:"No API key required. The request is sent directly to DuckDuckGo.",aiApiKey:"API key",aiApiKeyPlaceholder:"Paste the API key",aiModel:"Model",aiYou:"You",aiConfigure:"Configure connection",aiOpenSettings:"Configure connections",aiClose:"Close chat",aiConnectorMissing:"Connector not found.",aiProviderSetup:"Configure this provider's key and model.",aiUnknownFailure:"Unknown failure."},
  es:{aiTrigger:"Chat IA",aiEyebrow:"Comparador inteligente",aiTitle:"Chat de IA unificado",aiSubtitle:"Una pregunta, distintas perspectivas.",aiSettingsTitle:"Conexiones con proveedores",aiSettingsWarning:"Las claves permanecen solo en este navegador. En producción, usa un backend que guarde los secretos en el servidor.",aiCancel:"Cancelar",aiSave:"Guardar conexiones",aiParticipants:"IAs participantes",aiEmptyTitle:"Compara respuestas en segundos",aiEmptyDescription:"Haz una pregunta para ver cómo distintos asistentes abordan el mismo tema.",aiSuggestionLaunch:"Estrategia de lanzamiento",aiSuggestionConcept:"Explicar un concepto",aiSuggestionExperience:"Analizar una experiencia",aiInputLabel:"Mensaje para las IAs",aiPlaceholder:"Pregunta a todas las IAs...",aiSend:"Enviar",aiNotice:"Los mensajes se envían directamente a los proveedores seleccionados. Se aplican los costes y políticas de cada API.",aiConfigured:"API configurada",aiMissingKey:"Sin clave",aiNoKeyRequired:"No requiere clave de API. La solicitud se envía directamente a DuckDuckGo.",aiApiKey:"Clave de API",aiApiKeyPlaceholder:"Pega la clave de API",aiModel:"Modelo",aiYou:"Tú",aiConfigure:"Configurar conexión",aiOpenSettings:"Configurar conexiones",aiClose:"Cerrar chat"}
};

export function chatT(key) { return chatTranslations[language]?.[key] || chatTranslations.en[key] || key; }

export const greetings = { pt:["Bom dia","Boa tarde","Boa noite"], en:["Good morning","Good afternoon","Good evening"], es:["Buenos días","Buenas tardes","Buenas noches"], fr:["Bonjour","Bon après-midi","Bonsoir"], de:["Guten Morgen","Guten Tag","Guten Abend"], it:["Buongiorno","Buon pomeriggio","Buonasera"], nl:["Goedemorgen","Goedemiddag","Goedenavond"], pl:["Dzień dobry","Dzień dobry","Dobry wieczór"], ru:["Доброе утро","Добрый день","Добрый вечер"], tr:["Günaydın","İyi günler","İyi akşamlar"], ar:["صباح الخير","مساء الخير","مساء الخير"], hi:["सुप्रभात","नमस्कार","शुभ संध्या"], zh:["早上好","下午好","晚上好"], ja:["おはようございます","こんにちは","こんばんは"], ko:["좋은 아침입니다","안녕하세요","좋은 저녁입니다"] };

export let language = localStorage.getItem(STORAGE_KEYS.language) || navigator.language.slice(0, 2);
if (!translations[language]) language = "en";
export const t = (key) => translations[language]?.[key] || translations.en[key] || key;
export function label(group) {
  const groups = { removeImage:removeImageLabels, openSite:openSiteLabels, language:languageLabels, shortcuts:shortcutFilterLabels, pageTitle:pageTitleLabels, clear:clearLabels, creator:creatorLabels };
  return groups[group]?.[language] || groups[group]?.en || group;
}
export function setLanguage(nextLanguage) { language = translations[nextLanguage] ? nextLanguage : "en"; localStorage.setItem(STORAGE_KEYS.language, language); }
export function getGreeting(hour) { const values = greetings[language] || greetings.en; return values[hour < 12 ? 0 : hour < 18 ? 1 : 2]; }
export function getLocale() {
  const browserLocale = navigator.language;
  return browserLocale.toLowerCase().startsWith(`${language.toLowerCase()}-`) ? browserLocale : languageLocales[language] || "en-US";
}
